services:
  - type: web
    name: nodejs-test-backend
    runtime: node
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 22
